FROM openjdk:8-jdk-alpine

VOLUME /tmp

EXPOSE 9100

ARG JAR_FILE=hse-railways-auth-resourse-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} hse-railways-auth-resourse-0.0.1-SNAPSHOT.jar

ENTRYPOINT [ "java", "-jar", "/hse-railways-auth-resourse-0.0.1-SNAPSHOT.jar" ]