FROM openjdk:8-jdk-alpine

VOLUME /tmp

EXPOSE 9000

ARG JAR_FILE=lib-auth-jwt-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} lib-auth-jwt-0.0.1-SNAPSHOT.jar

ENTRYPOINT [ "java", "-jar", "lib-auth-jwt-0.0.1-SNAPSHOT.jar" ]